apiVersion: v1
kind: ConfigMap
metadata:
  name: pulsecart-config
  namespace: pulsecart
data:
  DB_HOST: triad-dev-db.cqtfd12rqqvg.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: pulsecart
  DB_SSLMODE: require
  DB_USER: pulsecart
  ORDERS_URL: http://orders:8081
  REDIS_ADDR: master.triad-dev-redis.pvymvc.use1.cache.amazonaws.com:6379
  REDIS_TLS_ENABLED: "true"
  NATS_URL: nats://triad-nats.messaging.svc.cluster.local:4222
  NOTIFICATIONS_URL: http://notifications:8082
  WORKER_METRICS_PORT: "9091"
