apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pulsecart-db-password
  namespace: pulsecart
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: pulsecart-aws-secrets
    kind: SecretStore
  target:
    name: pulsecart-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:971146591534:secret:rds!db-b84b7356-92eb-43fd-bf93-df2842556b62-IxwMhw
        property: password
