apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pulsecart

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - api-gateway-deployment.yaml
  - api-gateway-service.yaml
  - orders-deployment.yaml
  - orders-service.yaml
  - notifications-deployment.yaml
  - notifications-service.yaml
  - worker-deployment.yaml
  - worker-service.yaml
  - ingress.yaml
