apiVersion: v1
kind: Secret
metadata:
  name: pulsecart-secrets
  namespace: pulsecart
type: Opaque
stringData:
  DATABASE_URL: postgres://pulsecart:REPLACE_ME@triad-postgres.default.svc.cluster.local:5432/pulsecart?sslmode=disable
