apiVersion: v1
kind: Secret
metadata:
  name: pulsecart-secrets
  namespace: pulsecart
type: Opaque
stringData:
  DATABASE_URL: postgres://pulsecart:REPLACE_ME_FROM_RDS_SECRET@triad-dev-db.cqtfd12rqqvg.us-east-1.rds.amazonaws.com:5432/pulsecart?sslmode=require
