services:
  postgres:
    image: postgres:16
    container_name: pulsecart-postgres
    environment:
      POSTGRES_USER: pulsecart
      POSTGRES_PASSWORD: pulsecart
      POSTGRES_DB: pulsecart
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulsecart"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pulsecart_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: pulsecart-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - pulsecart_redis:/data

  nats:
    image: nats:2
    container_name: pulsecart-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222"]

volumes:
  pulsecart_pg:
  pulsecart_redis:
